<?php

/**
 * PluginsbTestimonial
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsbTestimonial extends BasesbTestimonial
{
	public function getTitle()
	{
		return $this->getName() . ' ' . $this->getJobTitle() . ' ' . $this->getCompanyName();
	}

	public function save(Doctrine_Connection $con = null)
	{
		$slug = strtolower($this->getSlug());
		$slug = preg_replace("/[^a-z0-9\s-]/", "", $slug);
		$slug = trim(preg_replace("/\s+/", " ", $slug));
		$slug = preg_replace("/\s/", "-", $slug);
		$this->setSlug($slug);
		return parent::save($con);
	}
}
