<?php

/**
 * PluginsbTestimonialsSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbTestimonialsSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbTestimonialsSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbTestimonialsSlot');
    }
}